package xnt.github.hackerrank.treepreordertraversal;

import java.util.Scanner;

class Node {
    Node left;
    Node right;
    int data;

    Node(int data) {
        this.data = data;
        left = null;
        right = null;
    }
}

/**
 * https://www.hackerrank.com/challenges/tree-preorder-traversal/problem
 */
class Solution {

    /**
     * Recursively the tree in preorder traversal
     * @param root a pointer to the tree's root
     */
    public static void preOrder(Node root) {
        System.out.printf("%d ", root.data);

        if(root.left != null) {
            preOrder(root.left);
        }

        if(root.right != null) {
            preOrder(root.right);
        }
    }

    //<editor-fold desc="Autogenerated">
    public static Node insert(Node root, int data) {
        if(root == null) {
            return new Node(data);
        } else {
            Node cur;
            if(data <= root.data) {
                cur = insert(root.left, data);
                root.left = cur;
            } else {
                cur = insert(root.right, data);
                root.right = cur;
            }
            return root;
        }
    }

    public static void main(String[] args) {
        Scanner scan = new Scanner(System.in);
        int t = scan.nextInt();
        Node root = null;
        while(t-- > 0) {
            int data = scan.nextInt();
            root = insert(root, data);
        }
        scan.close();
        preOrder(root);
    }
    //</editor-fold>
}